### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by apjanke** [sdurrheimer/docker-compose-zsh-completion#1]
Should this repo include a LICENSE file? The main docker-compose repo [states that it's Apache licensed](https://github.com/docker/compose/blob/8346186469eb046ebd619727ac101c83322e698b/LICENSE), which requires redistribution under the same terms and with an Apache license notice included.

**Comment by sdurrheimer** [comment]
I think I can pretty much rest deprecate this since I'm now Maintaining the zsh completion via the docker/compose repo.

**Comment by sdurrheimer** [comment]
I've added the MIT licence to the repository, since this is the source projet of the official docker-compose zsh completion.
I don't think it will be a issue since MIT is [compatible](http://apache.org/legal/resolved.html#category-a) with Apache License.

**Comment by apjanke** [comment]
Thank you!
